name: Instagram Follower Tracker

on:
  schedule:
    # 毎日午前0:00（UTC）に実行
    - cron: '0 15 * * *'  # UTC 15:00 = 日本時間 0:00
  workflow_dispatch:  # 手動実行用

jobs:
  track-followers:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run follower tracker
        env:
          INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
          INSTAGRAM_LOGIN_USER: ${{ secrets.INSTAGRAM_LOGIN_USER }}
          INSTAGRAM_LOGIN_PASSWORD: ${{ secrets.INSTAGRAM_LOGIN_PASSWORD }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python instagram_follower_tracker.py
